version: '3'

services:
  panel:
    image: ghcr.io/pterodactyl/panel:latest
    container_name: pterodactyl_panel
    restart: always
    environment:
      - APP_URL=https://your-domain.com
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=panel
      - DB_USERNAME=paneluser
      - DB_PASSWORD=yourpassword
    volumes:
      - ./panel-data:/app/storage
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: pterodactyl_db
    restart: always
    environment:
      - MYSQL_DATABASE=panel
      - MYSQL_USER=paneluser
      - MYSQL_PASSWORD=yourpassword
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - ./db-data:/var/lib/mysql
