version: '3'

services:
  panel:
    image: ghcr.io/pterodactyl/panel:latest
    container_name: pterodactyl_panel
    restart: always
    environment:
      - APP_URL=http://localhost
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=panel
      - DB_USERNAME=pterodactyl
      - DB_PASSWORD=changeme
      - CACHE_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - SESSION_DRIVER=redis
      - REDIS_HOST=redis
    volumes:
      - ./panel-data:/app/storage
    ports:
      - "8080:80"
    depends_on:
      - db
      - redis

  db:
    image: mariadb:10.5
    container_name: pterodactyl_db
    restart: always
    environment:
      - MYSQL_DATABASE=panel
      - MYSQL_USER=pterodactyl
      - MYSQL_PASSWORD=changeme
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - ./db-data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: pterodactyl_redis
    restart: always
    volumes:
      - ./redis-data:/data
